### ISSUE TITLE
Problem running scripts manually because of relative paths

### ISSUE THREAD

**Issue by vbernardes** [WeAreFairphone/fprsmap#89]
Hi everyone,

I'm still relatively new to contributing to open-source projects, so I hope there's nothing too wrong with this submission.

I was following the instructions on the Wiki for locally building the map, and ran into two problems:

1. The `data` directory must be created before executing the scripts in the `scripts` directory, which was not addressed on the Wiki.
2. The scripts are not using absolute paths for the data files, so they break when run manually on the command line from within the `scripts` directory.

I don't know if these scripts are meant to be run manually very often, so I don't think it's a big issue, but an easy fix, nonetheless. Regarding the `data` directory, maybe an additional instruction on the Wiki will suffice.

P.S.: Please check out pull request #88 for the second issue.

**Comment by StefanBrand** [comment]
#88 looks very good. I'll look at it at home. :) Thanks for the contribution!

As for the missing `data` directory, this was addressed in #2f9e8d1, but had to be reverted because of course it prevented the downloaded data from being committed to the `gh-pages` branch. I had overlooked this. 

Ps: At the moment, the `data` directory is created at build time in Travis.

**Comment by StefanBrand** [comment]
I merged your PR. Thanks again! 😊 For the missing `data` directory, please continue in #90
